# Generated by Django 3.0.6 on 2020-05-28 00:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateInformation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('information_date', models.DateTimeField(verbose_name='Fecha de Creacion')),
            ],
        ),
        migrations.CreateModel(
            name='MetrobusUnitInformation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('vehicle_id', models.CharField(max_length=10)),
                ('trip_start_date', models.CharField(max_length=10)),
                ('position_longitude', models.FloatField(max_length=25)),
                ('position_latitude', models.FloatField(max_length=25)),
                ('information_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metrobus.UpdateInformation')),
            ],
        ),
    ]
