# Generated by Django 3.0.6 on 2020-05-28 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrobus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metrobusunitinformation',
            name='trip_start_date',
        ),
        migrations.AlterField(
            model_name='updateinformation',
            name='information_date',
            field=models.DateTimeField(verbose_name='Fecha de la Informacion'),
        ),
    ]
