# Generated by Django 3.0.6 on 2020-05-28 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrobus', '0002_auto_20200527_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrobusunitinformation',
            name='alcaldia',
            field=models.CharField(default='TEST', max_length=25),
            preserve_default=False,
        ),
    ]
